### ISSUE TITLE
Unreadable password field not in challenge but it is part of the solution

### ISSUE THREAD

**Issue by Roger-Heathcote** [oliverjam/learn-form-validation#4]
We hint at it by by saying "Here's a full list of validation attributes." but it's not mentioned anywhere in the related challenge, only in the solution so it's easily missed.

**Comment by oliverjam** [comment]
I think it's ok to leave non-critical things like that up to them to discover. It doesn't affect validation to use `type="text"` there, it's just a nice bonus if they do figure it out. Worst case they see it in the solution and learn it that way
